Basic named parameters
tcl2020/tcl pull request #1
Opened 2018-11-16 22:55 UTC by snoe925

Add -named-parameters to the proc command.

       proc [-named-parameters] name args body

If a proc is flagged with -named-parameters, then the argument list is re-written in the call frame.
The proc arguments are to be -name value -name value.

proc A {a b c} {...}
A -a 1 -b 2 -c 3

If the proc has default values for the arguments, then the parameter is optional. If a default value is not declared by the proc, then an error is raised.

Currently if the argument list grows because of parameter expansion, then the script will fail because of stack / script work checking.

2018-11-30 12:24 UTC, lehenbauer requested changes
Looks good.  I think the Tcl_AttemptAlloc needs to be fixed.  Other remarks are minor.

2018-11-30 12:24 UTC, lehenbauer commented on generic/tclProc.c
> +    /* For each passed argument, either copy to positional argv array. */
"either copy to positional argv array"... or what... what's the other half of the "either"?

2018-11-30 12:24 UTC, lehenbauer commented on generic/tclProc.c
> +                Tcl_Obj ** newNewObjv = (Tcl_Obj **)Tcl_AttemptAlloc(newObjc * sizeof(*newObjv));
Tcl_AttemptAlloc can fail.  You need to either confirm that it succeeded or replace the call with Tcl_Alloc.

2018-11-30 12:24 UTC, lehenbauer commented on generic/tclProc.c
> +    /* for any parameters not provided in the argument list supply the default
"for any parameters not provided in the argument list that have a default, supply the default
if a named parameter or generate an error if a positional parameter is not provided and doesn't have a default"

2018-11-30 23:31 UTC, snoe925 commented
To get the memory handling correct I had to make a Tcl List for the new call parameters.  That is easier if the list operations are appends.  Therefore, I had to rewrite most of the logic.
But overall I think it's a bit more clear what is going on.

2018-12-03 16:19 UTC, lehenbauer approved these changes
Approved... but please read through my comments and see if there's anything you think you should change.

2018-12-03 16:19 UTC, lehenbauer commented on generic/tclProc.c
> +        return TCL_ERROR;
Would hitting this mean there is a bug in the named parameter software?  If so then maybe make it be an assertion instead?

2018-12-03 16:19 UTC, lehenbauer commented on generic/tclProc.c
> +            if (markerIndex == 0 && name[0] == '-' && name[1] == '-' && !name[2]) {
I might've used "name[2] != '\0'" here for readability rather than "!name[2]", but no biggie.

2018-12-03 16:19 UTC, lehenbauer commented on generic/tclProc.c
> +     * Caching this information when compiling the proc would be faster. */
So every time any proc is called this code will loop through the arguments defined in the proc to look for --?

2018-12-03 16:19 UTC, lehenbauer commented on generic/tclProc.c
> +        Tcl_ListObjGetElements(NULL, copyPtr, &newObjc, &newObjv);
Tcl_ListObjGetElements can fail and return TCL_ERROR.  Perhaps that's not possible here, though.

2018-12-03 16:46 UTC, resuna commented
I still think we need to be able to have procs that accept both positional and named parameters, because it's such a commonly useful idiom. (eg gets, switch, etc).

proc --named-parameters foo {positional1 positional2 {-named default} ...} { ... }

2018-12-03 17:35 UTC, merged